# Lab notebook - week 2

###  A note about cell output - expressions vs. statements

In [6]:
# Some code fragments produce output, see the red "Out[?]" below - such fragments are called expressions.
5 + 2

7

In [7]:
# Other fragments produce no output. Such fragments are called statements. Not that there is no "Out[]" below this cell.
x = 5 + 2

In [8]:
# If you want to see the value of x, just write x on another line, "x" is an "expression" and produces the value of x as output
y = 3 + 7
y

10

In [9]:
# A cell only produces one output - that of the last expression in the cell
x  # value of x is not shown
y 

10

In [10]:
# If you want to see several values, output them from different cells or use print()
# note that print() produces text, but it is not labeled as Out[] (why?)
print(x)
print(y)

7
10


## NumPy basics
Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [11]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [12]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [13]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [14]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [15]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [16]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [17]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.25297752, 0.61787788, 0.73780522, 0.94020988, 0.54394232,
       0.13530754])

In [18]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([70, 59, 70, 36, 79, 23])

### Array properties

In [19]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [20]:
# The total number of elements
b.size 

6

In [21]:
# number of dimensions
b.ndim 

2

In [22]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [23]:
# Data type of the array
a.dtype

dtype('int32')

In [24]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [25]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


#### Convert a list into a numpy array

In [26]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [27]:
x = np.array(lst)
x

array([5, 3, 8, 4])

### What happens when you multiply a list by 3, what a about an array multiplied by 3?

##### What happens when you multiply a list by 3:

In [28]:
# Feel free to add more cells
lst*3

[5, 3, 8, 4, 5, 3, 8, 4, 5, 3, 8, 4]

##### A numpy array multiplied by 3:

In [29]:

x*3

array([15,  9, 24, 12])

#### Create an array of 10 ones

In [30]:
array = np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Found out that when you time an array with 10, it makes an array with 10 elements with that old array

#### Create an array of 10 fives

In [31]:
array10fives = np.array([5]*10)
array10fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50 (including 50)

In [32]:
array10to50range = np.arange(10,51)
array10to50range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of 10 random numbers between 0 and 5 (not integers)

Found out that I could time all results by 5! Fun little brain twister

In [47]:
randomArray0and5 = np.random.random(10)*5
randomArray0and5

array([4.37114794, 1.47502612, 4.24558366, 4.03829031, 1.44334153,
       0.31589552, 0.79892055, 2.15271412, 1.81147352, 4.9283158 ])

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2

Wondering, where th np.linspace is?

In [ ]:
np.linspace?

Signature: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.


In [52]:
np.linspace(0, 2, num=11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#### Create a 3 by 4 array of ones

Wonder.. how?

In [56]:
np.ones?

# oh thats how!
Signature: np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

In [57]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Create a 3 by 4 array of fives

In [58]:
np.ones((3,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

#### Create a 3x3 matrix with values ranging from 0 to 8 (use reshape)

In [61]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Element selection
Using the following arrays `a` and `m`

In [62]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
m = np.arange(1,22).reshape((3,7))
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Create an array containing... 
#### the first 4 elements of a

#### apparently, this is called slicing [:5]

In [66]:
first4 = a[:5]
first4

array([10, 11, 12, 13, 14])

#### the last 3 elements of a

In [81]:
last3 = a[::-1]
last3

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

Reversing the array, by incrementing by -1, then I can access the last three by accessing the first three in the reversed array

In [82]:
last3 = a[::-1][:3]
last3

array([20, 19, 18])

#### The middle elements of a from 15 to 18 inclusive

Found out, that if a range starts from ie. 10, then you can find the element which has the value of five, by the 15-10 = 5 and 18-10 = 8 (+1) due to how the subarray query works.

In [83]:
a[5:9]

array([15, 16, 17, 18])

#### The first column of m

Just to recap, what is "m"?

In [91]:
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

it seems, that I have to assign it this way:    m[row,column]
apparently it is a combination between indexing (selecting a row or a column) and an empty slicing [:] (empty)

In [104]:
m[:, 0]

array([ 1,  8, 15])

#### The middle row of m

No need for empty splice

In [107]:
m[1]

array([ 8,  9, 10, 11, 12, 13, 14])

#### The left 3 columns of m

empty splice for all rows, and :3 splice for only 3 first coloumns

In [111]:
m[:,:3]

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

# THIS IS WHERE I ENDED The bottom-right 2 by 2 square

array([[13, 14],
       [20, 21]])

#### (bonus) every other element of a  

array([10, 12, 14, 16, 18, 20])

#### Subtract 5 from each element of a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [104]:
# Hint
np.int8

numpy.int8